[build]
  command = "npm run build"


[build.environment]
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["!node_modules/puppeteer/.local-chromium/**"]
